DROP TABLE IF EXISTS SceneAudioFile;
DROP TABLE IF EXISTS AudioFiles;
DROP TABLE IF EXISTS Scenes;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
    Id CHAR(36) PRIMARY KEY, -- Guid stored as a string
    Username VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    UsedStorageBytes BIGINT NOT NULL DEFAULT 0,
    MaxStorageBytes BIGINT NOT NULL DEFAULT 52428800,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Scenes (
    Id CHAR(36) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    UserId CHAR(36) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE AudioFiles (
    Id CHAR(36) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    UserId CHAR(36) NOT NULL,
    FileSize BIGINT NOT NULL DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE SceneAudioFile (
    SceneId CHAR(36) NOT NULL,
    AudioFileId CHAR(36) NOT NULL,
    AudioType ENUM('Music', 'Ambient', 'SoundEffect') NOT NULL,
    PRIMARY KEY (SceneId, AudioFileId, AudioType),
    FOREIGN KEY (SceneId) REFERENCES Scenes(Id) ON DELETE CASCADE,
    FOREIGN KEY (AudioFileId) REFERENCES AudioFiles(Id) ON DELETE CASCADE
);